### ISSUE TITLE
clarify resource listeners

### ISSUE THREAD

**Issue by HarHarLinks** [Half-Shot/matrix-hookshot#120]
https://github.com/Half-Shot/matrix-hookshot/blob/e6dd83ac5bd57a9e189b74999879efb767331646/docs/setup.md#L68

some of these are implicitly clear to me, but others are not
- webhooks: the part that received webhooks
- widgets: ?
- metrics: prometheus metrics
- provisioning: provisioning api
- appservice: ? maybe the same as`bridge.bindAddress` and`bridge.port`?

additionally, please explain how these relate to keys such as `bridge.bindAddress` and `bridge.port`

**Comment by Half-Shot** [comment]
Webhooks is incoming messages from the services, like you said.

Widgets is the frontend for experimental Matrix widget support (most people don't want this on).

Metrics is as described.

Provisioning is as described.

Appservice should be dropped from this entirely, since it's not supported as a listener yet (hence why the other config keys exist for this)

**Comment by HarHarLinks** [comment]
> Widgets is the frontend for experimental Matrix widget support (most people don't want this on).

https://github.com/Half-Shot/matrix-hookshot/blob/e6dd83ac5bd57a9e189b74999879efb767331646/docs/setup.md#L70-L74

Perhaps then additionally to explaining, the documentation/example shouldn't suggest to turn it on.

Could you also clarify: would there be trouble if I did
```yaml
listeners:
  - port: 9001
    bindAddress: 127.0.0.1
    resources:
      - metrics
  - port: 9001
    bindAddress: 127.0.0.1
    resources:
      - provisioning
```

instead of
```yaml
listeners:
  - port: 9001
    bindAddress: 127.0.0.1
    resources:
      - metrics
      - provisioning
```
?

I'm working on [adding hookshot to matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1505) and the former would be much easier to to.

Reading through the docs I didn't find it entirely clear which of the resources listens to what api endpoints, though probably they're at least disjoint. However a complete overview would be very convenient for proper reverse proxying as I'm trying to do.
