### ISSUE TITLE
registration needs user pattern that allows generic.userIdPrefix

### ISSUE THREAD

**Issue by HarHarLinks** [Half-Shot/matrix-hookshot#162]
https://github.com/Half-Shot/matrix-hookshot/blob/f56105db9de8a8ed2ef4597c28d4e8d799a2cccd/registration.sample.yml#L7

https://github.com/Half-Shot/matrix-hookshot/blob/f56105db9de8a8ed2ef4597c28d4e8d799a2cccd/config.sample.yml#L56

I only have
```yaml
  users:
    - regex: "@_github_.*:{{ matrix_domain }}"
      exclusive: true
  aliases:
    - regex: "#github_.+:{{ matrix_domain }}"
      exclusive: true
```
but
```yaml
userIdPrefix: webhooks_
```

both as provided by the docs, and am getting error `Invalid user localpart for this application service.` on `http://matrix-nginx-proxy:12080/_matrix/client/r0/register?user_id=%40webhooks_...`, so may assume this is the reason?

Perhaps this is the time to mention that appservice-webhooks uses `_webhook` as prefix, so admins should take care these don't clash https://github.com/turt2live/matrix-appservice-webhooks/blob/a2ef5051fa8e7ba62b3a0035452bc76c9f6dc1f1/config/sample.yaml#L13

**Comment by HarHarLinks** [comment]
Is `@_github_` hardcoded for the github bridge, or should it actually match `userIdPrefix`?

**Comment by HarHarLinks** [comment]
Per [the dev in chat](https://matrix.to/#/!TlZdPIYrhwNvXlBiEk:half-shot.uk/$gawbeSarsWt2iekZ7DCFDkA0QX2m3CPpds4eKUuV6ZU?via=half-shot.uk&via=matrix.org&via=envs.net), the registration needs to be:

```
  users:
    - regex: "@_github_.*:foobar" # Where foobar is your homeserver's domain
      exclusive: true
    - regex: "@_gitlab_.*:foobar" # Where foobar is your homeserver's domain
      exclusive: true
    - regex: "@_jira_.*:foobar" # Where foobar is your homeserver's domain
      exclusive: true
    - regex: "@_webhooks_.*:foobar" # Where foobar is your homeserver's domain // depending on userIdPrefix setting in conf
      exclusive: true
```
